added sudo

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -28,14 +28,15 @@ jobs:
           sudo rm /usr/local/bin/aws
           sudo rm /usr/local/bin/aws_completer
           sudo rm -rf /usr/local/aws-cli
-      # - name: Verify that AWS CLI is not installed
-      #   run: |
-      #     if output=$(aws --version); then
-      #         echo "AWS installed"
-      #     else
-      #         echo "AWS removed"
-      #         exit 1
-      #     fi
+      - name: Verify that AWS CLI is not installed
+        run: |
+          if command -v aws --version >/dev/null 2>&1; then
+            echo "AWS binary not found"
+          else
+            echo "AWS binary found"
+            exit 1
+          fi
+
       # Refer to https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
       - name: Setting up AWS CLI
         run: |
@@ -43,8 +44,8 @@ jobs:
           # unzip ./aws-cli.zip
           # cp ./aws-cli /usr/local/aws-cli
           # rm -rf ./aws-cli
-          cp ./aws /usr/local/bin/aws
-          cp ./aws_completer /usr/bin/aws_completer
+          sudo cp ./aws /usr/local/bin/aws
+          sudo cp ./aws_completer /usr/bin/aws_completer
       - name: Verify AWS CLIE installation 
         run: |
           aws --version
